CREATE TABLE users
(
    userid INT(6)
    UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR
    (30) NOT NULL,
password VARCHAR
    (250) NOT NULL,
create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON
    UPDATE CURRENT_TIMESTAMP
    );
