CREATE TABLE courses
(
    course_id INT(6)
    UNSIGNED AUTO_INCREMENT PRIMARY KEY,
course_code VARCHAR
    (30) NOT NULL,
create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON
    UPDATE CURRENT_TIMESTAMP
    );
